### ISSUE TITLE
Form defaults and validtion

### ISSUE THREAD

**Issue by carlwilson** [veraPDF/veraPDF-rest#19]
- disable steps 2 & 3 until file selected

**Comment by carlwilson** [comment]
Moved default values to #15 where fixed.

**Comment by rstorey** [comment]
It seemed like this was already done - I can't click on step 2 or 3 circles, but I can click the next button. In my fork, I removed the default null hash from the JS-SHA1 input because it was confusing to my end users. I also removed the "JS-" part of the label from "JS-SHA1" input field. My users don't know or care what technology is used to generate the SHA1, so the JS- bit is confusing to them (they know what a SHA1 or MD5 fixity is). If you'd like a pull request, I'll submit one.
